public  class Arthimaticcalculations {
    public  void additionmethod(integer x, integer y) 
    {

integer z = x + y;
system.debug('Sum of' + x + ' + ' + y + ' = ' + z);

    }


public void subtractionmethod(integer x, integer y)
    {

integer z = x - y;
system.debug('subtraction of' + x + ' - ' + y + ' = ' + z );

    }


    public void multiplicationmethod(integer x, integer y, integer z)
    {

        integer m = x * y * z;
        system.debug('Multiplication of' + x + '*' + y +' *' + z + ' = ' + m );
    }

}
